#Lesson 1. Основные понятия и структуры PyTorch

In [ ]:
!pip install torch

In [3]:
import torch

1. Создайте случайный FloatTensor размера 3x4x5

In [5]:
tensor = torch.randn(3, 4, 5)
tensor

tensor([[[-0.1642,  1.0925, -0.4746, -0.4912,  0.5333],
         [ 0.7155, -1.7620,  0.1600, -0.2045,  1.2329],
         [ 0.0349, -1.1737, -0.2172,  0.3819,  1.2824],
         [ 0.2335, -1.0048,  0.3805,  1.2569,  1.6736]],

        [[-0.0971,  1.4230,  0.1014, -0.5253,  1.5567],
         [ 0.0033,  0.8997,  0.9143,  2.6218,  0.5613],
         [-0.8688,  1.7479,  0.1258,  0.5344,  0.5378],
         [-1.4868,  2.7693,  0.7715,  0.5080,  1.1852]],

        [[-0.1817,  0.7033,  0.5640, -0.3145, -0.2596],
         [ 0.6342, -0.0060,  0.1407,  0.4253,  0.2088],
         [ 3.0821,  0.7983, -1.0735,  0.9710, -0.8251],
         [ 0.6019,  1.4492, -0.1666,  0.6450, -0.4086]]])

2. Выведите его форму (shape)

In [6]:
tensor.shape

torch.Size([3, 4, 5])

3. Приведите его к форме 6х10

In [19]:
tensor = tensor.reshape(6,10)
tensor.shape

torch.Size([6, 10])

4. Создайте случайный IntTensor размера 10


In [17]:
tensor2 = torch.randint(10,size=(10,))
tensor2

tensor([6, 2, 1, 8, 0, 3, 6, 7, 5, 1])

5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [20]:
tensor.mul(tensor2)

tensor([[-9.8517e-01,  2.1851e+00, -4.7460e-01, -3.9293e+00,  0.0000e+00,
          2.1465e+00, -1.0572e+01,  1.1199e+00, -1.0227e+00,  1.2329e+00],
        [ 2.0929e-01, -2.3475e+00, -2.1724e-01,  3.0548e+00,  0.0000e+00,
          7.0059e-01, -6.0287e+00,  2.6632e+00,  6.2846e+00,  1.6736e+00],
        [-5.8278e-01,  2.8459e+00,  1.0145e-01, -4.2025e+00,  0.0000e+00,
          9.8872e-03,  5.3982e+00,  6.3999e+00,  1.3109e+01,  5.6129e-01],
        [-5.2130e+00,  3.4958e+00,  1.2579e-01,  4.2749e+00,  0.0000e+00,
         -4.4604e+00,  1.6616e+01,  5.4007e+00,  2.5402e+00,  1.1852e+00],
        [-1.0903e+00,  1.4067e+00,  5.6400e-01, -2.5157e+00, -0.0000e+00,
          1.9026e+00, -3.5886e-02,  9.8474e-01,  2.1263e+00,  2.0884e-01],
        [ 1.8492e+01,  1.5966e+00, -1.0735e+00,  7.7679e+00, -0.0000e+00,
          1.8058e+00,  8.6954e+00, -1.1665e+00,  3.2251e+00, -4.0865e-01]])

6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6


In [27]:
tensor.matmul(tensor.transpose(0,1))

tensor([[ 7.1755,  3.1161,  1.3298, -2.4455,  1.2039, -2.8266],
        [ 3.1161,  8.8060,  3.7794, -1.4297, -0.3158, -2.5358],
        [ 1.3298,  3.7794, 13.5780,  8.3300,  2.1942,  1.5484],
        [-2.4455, -1.4297,  8.3300, 16.5380,  0.7632,  1.4908],
        [ 1.2039, -0.3158,  2.1942,  0.7632,  1.6586, -0.1566],
        [-2.8266, -2.5358,  1.5484,  1.4908, -0.1566, 15.9857]])

7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [28]:
x = torch.tensor([1, 0.5, 2], requires_grad=True)
z = x**3 + x - 75*x
z.backward(x)
x.grad

tensor([ -71.0000,  -36.6250, -124.0000])

8. Создайте единичный тензор размера 5x6

In [30]:
ones = torch.ones((5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

9. Переведите его в формат numpy

In [32]:
ones.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)